### PR TITLE
Add support for named files in archives.

### PR DESCRIPTION
**Pull request by DrMarcII**
Add phantomjs support.
Some rules cleanup.

### CODE REVIEW

**Comment by DrMarcII** [comment]
test this please

**Comment by damienmg** [comment]
This is not live yet sorry :(

**Comment by DrMarcII** [comment]
No worries.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
And its now live :)

test this please

**Comment by DrMarcII** [comment]
test this please

**Comment by damienmg** [comment]
test this please

**Comment by damienmg** [comment]
retest this please

**Comment by damienmg** [comment]
retest this please

**Pull request merged**
